name: Elixir CI

on: push

jobs:
  test:
    runs-on: ubuntu-18.04
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        otp: ['23.1']
        elixir: ['1.10.4', '1.11.0']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: Install Dependencies
        shell: bash
        run: |
          apt-get update
          apt-get -qq -y install curl make build-essential git
          mix local.rebar --force
          mix local.hex --force
          [[ ! -z "$HEX_ORG_NAME" && ! -z "$HEX_ORG_TOKEN" ]] && mix hex.organization auth ${{ secrets.HEX_ORG_NAME }} --key ${{ secrets.HEX_KEY }} || echo "no hex org configured"
          mix deps.get
          
      - name: Run Tests
        run: mix test